### ISSUE TITLE
aur package install does not place binay in path

### ISSUE THREAD

**Issue by williamleven** [sidusIO/BooGroCha#21]
aur package installs to `/usr/bin/boogrocha/bgc` wich doesnt work as unless you add `/usr/bin/boogrocha` to $PATH

it should install to `/usr/bin/bgc`

**Comment by HerrNaN** [comment]
Updated the PKGBUILD in https://aur.archlinux.org/cgit/aur.git/commit/?h=boogrocha&id=9b4d1131836d7b8b90be94638c62e751cbe11c44
